#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

bash -c "$(curl -fsSL "https://sh.rustup.rs")"

sudo dnf install -y "zsh"

sh -c "$(wget "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh" -O -)"
chsh -s $(which zsh)

zsh -c "$(curl -fsSL "https://get.sdkman.io")"

zsh -i -c "
sdk install java \$(sdk list java | grep -E '21\\..*-tem' | head -1 | awk '{print \$NF}')
sdk install java \$(sdk list java | grep -E '17\\..*-tem' | head -1 | awk '{print \$NF}')
sdk install java \$(sdk list java | grep -E '11\\..*-tem' | head -1 | awk '{print \$NF}')
sdk install maven
sdk install gradle
sdk install kotlin
sdk install scala
sdk install sbt
" </dev/null

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh")"
