#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by distroscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/distroscript
# -----------------------------------------------------------------------------

set -e

sudo dnf install -y "zsh"

rm -rf "$HOME/.oh-my-zsh"

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh")"

sudo dnf install -y "python3-pip"

tee -a "$HOME/.zshrc" <<'EOF'
# pip
export PATH="$HOME/.local/bin:$PATH"
EOF

pip install -U "kazam"
